# Generated by Django 4.2.20 on 2025-04-17 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organisation_details', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectsDetails',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=255)),
                ('product_mail', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='attachments/')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('project_name', 'product_mail')},
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('member_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectid_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projectid_modified_by', to=settings.AUTH_USER_MODEL)),
                ('project_asignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_engineer', to='organisation_details.employee')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects_details.projectsdetails')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
