# Generated by Django 4.2.20 on 2025-04-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='level',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='tree_id',
        ),
    ]
