# Generated by Django 4.2.20 on 2025-04-17 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_details', '0001_initial'),
        ('projects_details', '0002_remove_projectmember_level_remove_projectmember_lft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsdetails',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_organisation', to='organisation_details.organisation'),
        ),
    ]
