# Generated by Django 4.2.20 on 2025-04-17 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects_details', '0003_projectsdetails_organisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmember',
            name='project_asignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_engineer', to=settings.AUTH_USER_MODEL),
        ),
    ]
