# Generated by Django 5.1.5 on 2025-04-09 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0002_remove_ticket_contact_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact_mode',
            field=models.CharField(choices=[('email', 'Email'), ('phone', 'Phone')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
