# Generated by Django 5.1.5 on 2025-04-10 13:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0003_ticket_contact_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 10, 13, 5, 57, 359886, tzinfo=datetime.timezone.utc)),
        ),
    ]
