# Generated by Django 5.1.5 on 2025-04-10 13:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0005_alter_slatimer_start_time_alter_ticket_pre_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 10, 13, 30, 42, 513634, tzinfo=datetime.timezone.utc)),
        ),
    ]
