# Generated by Django 5.1.5 on 2025-04-11 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0006_alter_slatimer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 8, 35, 49, 671971, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='SLATimeHistory',
        ),
    ]
