# Generated by Django 5.1.5 on 2025-04-11 09:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0007_alter_slatimer_start_time_delete_slatimehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatimer',
            name='sla_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Paused', 'Paused'), ('Stopped', 'Stopped')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='slatimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 9, 0, 23, 617384, tzinfo=datetime.timezone.utc)),
        ),
    ]
