# Generated by Django 5.1.5 on 2025-04-11 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0008_slatimer_sla_status_alter_slatimer_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='slatimer',
            name='warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='slatimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 11, 10, 2, 36, 692712, tzinfo=datetime.timezone.utc)),
        ),
    ]
