# Generated by Django 4.2.20 on 2025-04-18 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0020_remove_ticket_contact_mode_alter_slatimer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 11, 52, 4, 457150, tzinfo=datetime.timezone.utc)),
        ),
    ]
