# Generated by Django 4.2.20 on 2025-04-18 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0022_alter_slatimer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 12, 34, 25, 110261, tzinfo=datetime.timezone.utc)),
        ),
    ]
