# Generated by Django 4.2.20 on 2025-04-18 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0028_alter_slatimer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 18, 19, 2, 16, 944395, tzinfo=datetime.timezone.utc)),
        ),
    ]
