# Generated by Django 4.2.20 on 2025-04-19 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0036_alter_slatimer_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='slatimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 7, 58, 14, 620121, tzinfo=datetime.timezone.utc)),
        ),
    ]
