# Generated by Django 4.2.20 on 2025-04-19 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0038_alter_slatimer_start_time_alter_ticket_assignee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 19, 52, 2, 572569, tzinfo=datetime.timezone.utc)),
        ),
    ]
