# Generated by Django 4.2.20 on 2025-04-19 20:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0041_alter_slatimer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 20, 4, 46, 318798, tzinfo=datetime.timezone.utc)),
        ),
    ]
