# Generated by Django 4.2.20 on 2025-04-20 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0042_alter_slatimer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 5, 34, 51, 758978, tzinfo=datetime.timezone.utc)),
        ),
    ]
