# Generated by Django 4.2.20 on 2025-04-20 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0045_alter_slatimer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 20, 7, 33, 20, 663160, tzinfo=datetime.timezone.utc)),
        ),
    ]
