# Generated by Django 5.1.5 on 2025-04-26 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0048_alter_slatimer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 26, 9, 57, 1, 237903, tzinfo=datetime.timezone.utc)),
        ),
    ]
