# Generated by Django 5.1.5 on 2025-04-27 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0061_alter_slatimer_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slatimer',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 27, 5, 10, 45, 813938, tzinfo=datetime.timezone.utc)),
        ),
    ]
