# Generated by Django 5.1.5 on 2025-04-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solution_groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutiongroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
