# Generated by Django 4.2.20 on 2025-04-18 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timer', '0019_alter_slatimer_start_time'),
        ('solution_groups', '0002_solutiongroup_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionGroupTickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_grouop_id_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_group_id_modified_by', to=settings.AUTH_USER_MODEL)),
                ('solution_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_group', to='solution_groups.solutiongroup')),
                ('ticket_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_groups_tickets', to='timer.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_group_engineer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
