# Generated by Django 4.2.20 on 2025-04-20 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solution_groups', '0003_solutiongrouptickets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutiongrouptickets',
            name='solution_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_group_tickets', to='solution_groups.solutiongroup'),
        ),
    ]
