# Generated by Django 5.1.1 on 2025-05-03 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='parent_organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_organisations', to='organisation_details.organisation'),
        ),
    ]
