# Generated by Django 4.2.20 on 2025-04-18 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_details', '0001_initial'),
        ('priority', '0002_priority_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_priority', to='organisation_details.organisation'),
        ),
    ]
