# Generated by Django 5.1.5 on 2025-04-27 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_creation', '0002_add_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
