# Generated by Django 5.1.5 on 2025-04-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles_creation', '0003_rolepermission_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
