# Generated by Django 5.1.1 on 2025-05-02 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
