# Generated by Django 5.1.1 on 2025-05-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_details', '0002_remove_userprofile_emp_id_userprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emp_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
