# Generated by Django 5.1.1 on 2025-05-02 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation_details', '0001_initial'),
        ('personal_details', '0004_remove_userprofile_emp_id_userprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='employee',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='organisation_details.employee'),
            preserve_default=False,
        ),
    ]
