# Generated by Django 4.2.20 on 2025-04-18 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0028_alter_slatimer_start_time'),
        ('History', '0003_remove_reports_file_reportfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_attach', to='timer.ticket')),
            ],
        ),
        migrations.DeleteModel(
            name='ReportFile',
        ),
    ]
