# Generated by Django 4.2.20 on 2025-04-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0004_attachment_delete_reportfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='ticket',
        ),
        migrations.AddField(
            model_name='attachment',
            name='Reports',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_attach', to='History.reports'),
            preserve_default=False,
        ),
    ]
