# Generated by Django 4.2.20 on 2025-04-18 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('History', '0005_remove_attachment_ticket_attachment_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='Reports',
        ),
        migrations.AddField(
            model_name='attachment',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='report_attachments', to='History.reports'),
            preserve_default=False,
        ),
    ]
