# Generated by Django 4.2.20 on 2025-04-18 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timer', '0033_alter_slatimer_start_time'),
        ('History', '0006_remove_attachment_reports_attachment_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_attach_ticket', to='timer.ticket'),
        ),
    ]
